import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { LabReport } from "./types.js";
const escape = (s: string) => s.replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
export async function writeLabReport(directory: string, report: LabReport): Promise<void> {
  await mkdir(directory, { recursive: true });
  await writeFile(path.join(directory, "report.json"), `${JSON.stringify(report, null, 2)}\n`);
  await writeFile(path.join(directory, "index.html"), renderLabReport(report));
}
export function renderLabReport(r: LabReport): string {
  const passed = r.events.filter(e => e.status === "passed").length;
  const failed = r.events.filter(e => e.status === "failed").length;
  const result = r.infrastructureFailure ? "ABORTED" : r.passed ? "PASSED" : "FAILED";
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(r.name)} · Hedera Lab</title>
<style>
:root{color-scheme:dark;font:15px/1.6 system-ui,sans-serif;background:#0b1017;color:#dbe4ef}*{box-sizing:border-box}body{margin:0}header{border-bottom:1px solid #253344;padding:22px 5vw;display:flex;justify-content:space-between;align-items:center}.brand{font-weight:700;letter-spacing:.08em;color:#fafcff}.brand span{color:#6ee7be}main{max-width:1120px;margin:48px auto;padding:0 24px}.eyebrow{color:#91a3b9;font-size:12px;letter-spacing:.13em;text-transform:uppercase}h1{font-size:clamp(28px,5vw,44px);line-height:1.15;margin:12px 0 16px}h2{font-size:19px}.muted{color:#91a3b9}.badge{padding:5px 10px;border-radius:5px;font:600 12px monospace;background:#1c3040;color:#b4d8ff}.passed{color:#6ee7be}.failed{color:#ffa19c}.skipped{color:#91a3b9}.notice{border-left:3px solid #71b7ff;background:#111f2e;padding:15px 20px;margin:25px 0}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:28px 0}.stat{background:#121c28;border:1px solid #263446;padding:18px;border-radius:8px}.stat strong{display:block;font-size:26px}.toolbar{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:30px 0 16px}button{font:inherit;color:#c7d6e8;background:#121c28;border:1px solid #34485f;border-radius:6px;padding:7px 14px;cursor:pointer}button[aria-pressed=true]{background:#254f46;color:#aeffdf;border-color:#62c7a0}details{background:#111a25;border:1px solid #263446;margin:10px 0;border-radius:8px}summary{cursor:pointer;padding:17px;display:grid;grid-template-columns:85px 1fr 85px;gap:12px;align-items:center}summary small{display:block;color:#91a3b9}pre{overflow:auto;white-space:pre-wrap;word-break:break-word;background:#09111b;margin:0 16px 16px;padding:16px;font:12px/1.7 ui-monospace,monospace;border-radius:6px}footer{border-top:1px solid #253344;margin-top:40px;padding:24px 0;color:#91a3b9;font-size:12px;overflow-wrap:anywhere}.resources summary{display:block}a{color:#91c8ff}@media(max-width:650px){.stats{grid-template-columns:repeat(2,1fr)}summary{grid-template-columns:70px 1fr}summary>time{display:none}}
</style></head><body><header><div class="brand">HEDERA <span>LAB</span></div><span class="badge">${escape(r.mode.toUpperCase())}</span></header><main>
<div class="eyebrow">Scenario evidence / ${escape(r.runId)}</div><h1>${escape(r.name)}</h1><span class="badge ${r.passed ? "passed" : "failed"}">${result}</span> <span class="muted">${escape(r.startedAt)} · ${r.browserExecuted ? "Browser exercised" : "Ledger scenario"}</span>
<div class="notice">${r.mode === "simulated" ? "Simulated ledger. These results verify application behavior against fixtures; they do not prove Hedera network behavior." : "Live SDK transactions. Inspect each assertion for its network evidence and the cleanup event for remaining resources."}</div>
<div class="stats"><div class="stat"><span class="muted">Checks passed</span><strong class="passed">${passed}</strong></div><div class="stat"><span class="muted">Failures</span><strong class="failed">${failed}</strong></div><div class="stat"><span class="muted">Transactions</span><strong>${r.events.filter(e => e.kind === "transaction").length}</strong></div><div class="stat"><span class="muted">Elapsed</span><strong>${(r.durationMs / 1000).toFixed(1)}s</strong></div></div>
<h2>Execution timeline</h2><div class="toolbar" aria-label="Filter timeline">${["all", "failed", "transaction", "assertion", "browser"].map(f => `<button type="button" data-filter="${f}" aria-pressed="${f === "all"}">${f[0].toUpperCase() + f.slice(1)}</button>`).join("")}</div>
<div id="timeline">${r.events.map(e => `<details data-kind="${e.kind}" data-status="${e.status}" ${e.status === "failed" ? "open" : ""}><summary><span class="${e.status}">${e.status.toUpperCase()}</span><div>${escape(e.message)}<small>${escape(e.id)} · ${e.kind}</small></div><time>${e.durationMs} ms</time></summary><pre>${escape(JSON.stringify(e.evidence ?? { at: e.at }, null, 2))}</pre></details>`).join("")}</div>
<h2>Provisioned resources</h2><details class="resources"><summary>Accounts, tokens and topics</summary><pre>${escape(JSON.stringify(r.resources, null, 2))}</pre></details>
<footer>Scenario: ${escape(r.scenarioPath)}<br>SHA-256: ${escape(r.scenarioHash)}<br><a href="report.json">Open machine-readable evidence</a></footer></main>
<script>document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));const f=button.dataset.filter;document.querySelectorAll('#timeline details').forEach(e=>e.hidden=!(f==='all'||e.dataset.kind===f||e.dataset.status===f));}));</script></body></html>`;
}
